name: zonnedauw
recipe: drupal8
config:
  drush: false
  php: '7.2'
  webroot: web
services:
  appserver:
    build:
      - composer install
tooling:
  behat:
    service: appserver
    cmd: /app/vendor/bin/behat
  robo:
    service: appserver
    cmd: /app/vendor/bin/robo
