name: ${LANDO_PROJECT_NAME}
recipe: drupal9
config:
  composer: 2
  drush: false
  php: '7.4'
  webroot: web
services:
  appserver:
    build:
      - composer install
    scanner: false
tooling:
  behat:
    service: appserver
    cmd: /app/vendor/bin/behat
  robo:
    service: appserver
    cmd: /app/vendor/bin/robo
  update-drupal:
    service: appserver
    description: Performs a Drupal database update.
    dir: /app
    cmd: ./vendor/bin/drush deploy --yes
  check-config:
    service: appserver
    description: Checks that the exported Drupal config is up to date.
    dir: /app
    cmd: './vendor/bin/drush config:status 2>&1 | grep "No differences" || echo "Error: config is not up-to-date. Run ''lando drush cex'' and commit changes." && false'
